---
- name: Get the IP for the current admin WS
  import_tasks: tasks/admin_ws_ip.yml

- name: create directory on admin WS to hold configurations
  become: false
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ cluster_configurations_path }}" 
    - "{{ cluster_kubeconfig_path }}"
    - "{{ log_directory }}"
    - "{{ secrets_directory }}"

- name: Copy Anthos Secrets to admin WS
  become: false
  copy:
    src: "{{ secrets_path }}"
    dest: "{{ gkeadm_basedir }}/{{ secrets_directory }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy cluster configuration files to admin WS
  become: false
  template:
    src: "{{ item.type }}-cluster-config.yaml.j2"
    dest: "{{ cluster_configurations_path }}/{{ item.name }}.yaml"
  with_items: "{{ gke_cluster_config }}"

- name: Copy cluster IP configuration files to admin WS
  become: false
  template:
    src: static-ip.yaml.j2
    dest: "{{ cluster_configurations_path }}/{{ item.name }}-ip.yaml"
  with_items: "{{ gke_cluster_config }}"
  when: "'static' in item.gkenode_net.mode"

- name: Running gkectl prepare to initialize vSphere Environment for Anthos GKE on-prem
  become: false
  command: >
    gkectl prepare --config {{ cluster_configurations_path }}/{{ item.name }}.yaml
    --log_file ./logs/cluster-{{ item.name }}-prepare.log 
    {{ gkectl_prepare_flags }}
  delegate_to: gke-admin-ws
  register: gke_admin_cluster_prepare
  when: > 
     gkectl_run_prepare
     and 'admin' in item.type
  loop: "{{ gke_cluster_config }}"
  until: gke_admin_cluster_prepare.rc == 0
  retries: 2
  delay: 2

- name: Check Anthos GKE on-prem Admin Cluster Configuration
  become: false
  command: >
    gkectl check-config --config {{ cluster_configurations_path }}/{{ item.name }}.yaml
    --log_file ./logs/cluster-{{ item.name }}-checkconfig.log 
    {{ gkectl_check_flags }}
  delegate_to: gke-admin-ws
  register: gke_admin_cluster_check
  when: > 
     enable_config_check
     and create_admin_cluster
     and 'admin' in item.type
  loop: "{{ gke_cluster_config }}"
  until: gke_admin_cluster_check.rc == 0
  retries: 2
  delay: 2

- name: Create Anthos GKE on-prem Admin Cluster 
  become: false
  command: >
    gkectl create cluster --config {{ cluster_configurations_path }}/{{ item.name }}.yaml
    --kubeconfig-out {{ cluster_kubeconfig_path }}/{{ admin_cluster_kubeconfig }} 
    --log_file ./logs/cluster-{{ item.name }}-create.log
    {{ gkectl_create_flags }}
  delegate_to: gke-admin-ws
  register: gke_admin_cluster_create
  when: >
    create_admin_cluster
    and 'admin' in item.type
  loop: "{{ gke_cluster_config }}"
  until: gke_admin_cluster_create.rc == 0
  retries: 2
  delay: 2

- name: Output Admin Cluster Create Status
  debug:
    msg: 
      - "{{ gke_admin_cluster_create | json_query('results[].stdout_lines') }}"
  when: create_admin_cluster

- name: Output Admin Cluster Create Status FULL
  debug:
    msg: "{{ gke_admin_cluster_create }}" 
    verbosity: 3

- name: Check Anthos GKE on-prem User Cluster Configuration
  become: false
  command: >
    gkectl check-config --kubeconfig {{ cluster_kubeconfig_path }}/{{ admin_cluster_kubeconfig }} 
    --config {{ cluster_configurations_path }}/{{ item.name }}.yaml
    --log_file ./logs/user-cluster-{{ item.name.split('.')[0] }}-checkconfig.log 
    {{ gkectl_check_flags }}
  register: gke_user_cluster_check
  delegate_to: gke-admin-ws
  when: > 
    enable_config_check
    and create_user_cluster
    and 'user' in item.type
  loop: "{{ gke_cluster_config }}"
  until: gke_user_cluster_check.rc == 0 
  retries: 2
  delay: 2

- name: Create Anthos GKE on-prem User Cluster
  become: false
  command: >
    gkectl create cluster --kubeconfig {{ cluster_kubeconfig_path }}/{{ admin_cluster_kubeconfig }}
    --config {{ cluster_configurations_path }}/{{ item.name }}.yaml
    --log_file ./logs/user-cluster-{{ item.name.split('.')[0] }}-create.log
    {{ gkectl_create_flags }}
  register: gke_user_cluster_create
  delegate_to: gke-admin-ws
  when: > 
    create_user_cluster
    and 'user' in item.type
  loop: "{{ gke_cluster_config }}"
  until: gke_user_cluster_create.rc == 0 
  retries: 2
  delay: 2

- name: Output Cluster Create Status FULL
  debug:
    msg: "{{ gke_user_cluster_create }}" 
    verbosity: 3

- name: Output Cluster Create Status Parsed
  debug:
    msg: "{{ gke_user_cluster_create | json_query('results[].stdout_lines') }}"
