###                                                                             
# Copyright (2020) Hewlett Packard Enterprise Development LP                    
#                                                                               
# Licensed under the Apache License, Version 2.0 (the "License");               
# You may not use this file except in compliance with the License.              
# You may obtain a copy of the License at                                       
#                                                                               
# http://www.apache.org/licenses/LICENSE-2.0                                    
#                                                                               
# Unless required by applicable law or agreed to in writing, software           
# distributed under the License is distributed on an "AS IS" BASIS,             
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.      
# See the License for the specific language governing permissions and           
# limitations under the License.                                                
###                                                                             
---
# tasks file for anthos_admin_config

# Configure anthos admin base env var file
- name: Create env file used by bash scripts
  template:
    src: gcloud-proxy-vars.j2
    dest: "/home/{{ ansible_user }}/gcloud-proxy-vars"
    owner: ubuntu
    group: ubuntu
    mode: 0644
  when: proxy_enabled

- name: Add project to gcloud config
  become: false
  command: |
    gcloud config set project "{{ gcloud_project }}" 
  register: gcloud_config_out

- debug:
    msg: "{{ gcloud_config_out }}"
    verbosity: 2

- name: Install packages for monitoring and python pip
  apt:
    name:
      - lnav
      - python3-pip
    update_cache: yes
    state: present

- name: Update the gcloud SDK
  apt:
    name: "{{ cloud_sdk_pkgs }}"
    only_upgrade: yes
    update_cache: yes
    force_apt_get: yes
    force: yes
  when: apt_module_fixed is defined

# Wicked big hack because apt module won't do any upgrades if any package isn't installed
- name: Update the gcloud SDK
  shell: >
    apt-get update &&
    apt-get -y --only-upgrade install kubectl google-cloud-sdk google-cloud-sdk-app-engine-grpc google-cloud-sdk-pubsub-emulator
     google-cloud-sdk-app-engine-go google-cloud-sdk-firestore-emulator google-cloud-sdk-cloud-build-local
     google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-cbt
     google-cloud-sdk-bigtable-emulator google-cloud-sdk-app-engine-python-extras google-cloud-sdk-datalab google-cloud-sdk-app-engine-java
  failed_when: false