---
# tasks file for anthos_admin_config

# Configure anthos admin base env var file
- name: Create env file used by bash scripts
  template:
    src: gcloud-proxy-vars.j2
    dest: "/home/{{ ansible_user }}/gcloud-proxy-vars"
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Add project to gcloud config
  become: false
  command: |
    gcloud config set project "{{ gcloud_project }}" 
  register: gcloud_config_out

- debug:
    msg: "{{ gcloud_config_out }}"
    verbosity: 2

- name: Update the gcloud SDK
  apt:
    name: "{{ cloud_sdk_pkgs }}"
    only_upgrade: yes
    update_cache: yes
    force_apt_get: yes
    force: yes
  when: apt_module_fixed is defined

# Wicked big hack because apt module won't do any upgrades if any package isn't installed
- name: Update the gcloud SDK
  shell: >
    apt-get update &&
    apt-get -y --only-upgrade install kubectl google-cloud-sdk google-cloud-sdk-app-engine-grpc google-cloud-sdk-pubsub-emulator
     google-cloud-sdk-app-engine-go google-cloud-sdk-firestore-emulator google-cloud-sdk-cloud-build-local
     google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-cbt
     google-cloud-sdk-bigtable-emulator google-cloud-sdk-app-engine-python-extras google-cloud-sdk-datalab google-cloud-sdk-app-engine-java
  failed_when: false