---
# tasks file for F5_host_config
- name: Set hostname of BIG-IP
  bigip_hostname:
    hostname: "{{ f5.hostname }}"
    provider: "{{ f5.provider }}"
  delegate_to: localhost

- name: Set new admin password
  bigip_user:
    state: present
    username_credential: "{{ f5.admin_username }}"
    password_credential: "{{ f5.admin_password }}"
    provider: "{{ f5.provider }}"
    update_password: always
  delegate_to: localhost