---
# tasks file for F5_network_config
- name: Add VLAN 1700 as untagged to interface 1.1
  bigip_vlan:
    untagged_interface: 1.1
    name: "{{ f5.internal_vlan_name }}"
    tag: "{{ f5.internal_vlan_tag }}"
    provider: "{{ f5.provider }}"
  delegate_to: localhost

- name: Add VLAN 1732 as untagged to interface 1.2
  bigip_vlan:
    untagged_interface: 1.2
    name: "{{ f5.external_vlan_name }}"
    tag: "{{ f5.external_vlan_tag }}"
    provider: "{{ f5.provider }}"
  delegate_to: localhost

- name: Create Self IP for internal VLAN
  bigip_selfip:
    address: "{{ f5.internal_vlan_selfip }}"
    name: "{{ f5.internal_vlan_selfip_name }}"
    netmask: "{{ f5.internal_vlan_selfip_netmask }}"
    vlan: "{{ f5.internal_vlan_name }}"
    provider: "{{ f5.provider }}"
  delegate_to: localhost

- name: Create Self IP for external VLAN
  bigip_selfip:
    address: "{{ f5.external_vlan_selfip }}"
    name: "{{ f5.external_vlan_selfip_name }}"
    netmask: "{{ f5.external_vlan_selfip_netmask }}"
    vlan: "{{ f5.external_vlan_name }}"
    provider: "{{ f5.provider }}"
  delegate_to: localhost