---

- import_playbook: playbooks/get_prereq.yml
- import_playbook: playbooks/bigip_anthos.yml
- import_playbook: playbooks/deploy_admin_wrkst.yml
- import_playbook: playbooks/create_cluster.yml
- import_playbook: playbooks/csi.yml
- import_playbook: playbooks/service_mesh.yml
