###                                                                             
# Copyright (2020) Hewlett Packard Enterprise Development LP                    
#                                                                               
# Licensed under the Apache License, Version 2.0 (the "License");               
# You may not use this file except in compliance with the License.              
# You may obtain a copy of the License at                                       
#                                                                               
# http://www.apache.org/licenses/LICENSE-2.0                                    
#                                                                               
# Unless required by applicable law or agreed to in writing, software           
# distributed under the License is distributed on an "AS IS" BASIS,             
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.      
# See the License for the specific language governing permissions and           
# limitations under the License.                                                
###                                                                             
---
# tasks file for userdata

- name: Copy over ssh config files needed for git access
  copy:
    src: "{{ ssh_config_path }}"
    dest: /home/{{ ansible_user }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    force: no
    mode: 0600
  when: "'anthos_admin' in group_names"

- name: Debug
  debug:
     msg: "The ansible user is {{ ansible_ssh_user }}"
     verbosity: 2

# git pull HPE repo for deploying and configuring Anthos GKE on-prem
# This will only execute on the GKE admin workstation
- name: Pull HPE repo for Anthos deployment
  become: no
  git:
    repo: "{{ anthos_deploy_git.repo_url }}"
    dest: "/home/{{ ansible_user }}/{{ anthos_deploy_git.repo_name }}"
  when: 
    - anthos_deploy_git.pull_enable
    - "'anthos_admin' in group_names"

# git pull user data from a git repo. Existing GCP service account keys, ssh keys, ssl certs
# Depends on having an ssh config file present in user's .ssh directory configured for git access
# This only executes on the ansible controller (i.e. localhost).
- name: Pull userdata repo
  become: no
  git:
    repo: "{{ anthos_userdata_git.repo_url }}"
    dest: "/home/{{ ansible_user }}/{{ secrets_directory }}"
  when: 
    - anthos_userdata_git.pull_enable
    - "'local' in group_names"
  register: userdata_gitpulled

- name: Check if secrets were pulled from git
  stat:
    path: "{{ secrets_path }}/.git"
  when:
    - "'local' in group_names"
  register: git_secrets

- name: Fix permissions on ssh private key
  file:
    path: "{{ secrets_path }}/{{ gke_admin_workstation.ssh_private_key }}"
    mode: 0600
  when: 
    - "'local' in group_names"
