---
# tasks file for userdata

- name: Copy over ssh config files needed for git access
  copy:
    src: "{{ ssh_config_path }}"
    dest: /home/{{ ansible_user }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    force: no
    mode: 0600
  when: "'anthos_admin' in group_names"

- name: Debug
  debug:
     msg: "The ansible user is {{ ansible_ssh_user }}"
     verbosity: 2

# git pull HPE repo for deploying and configuring Anthos GKE on-prem
# This will only execute on the GKE admin workstation
- name: Pull HPE repo for Anthos deployment
  become: no
  git:
    repo: "{{ anthos_deploy_git.repo_url }}"
    dest: "/home/{{ ansible_user }}/{{ anthos_deploy_git.repo_name }}"
  when: 
    - anthos_deploy_git.pull_enable
    - "'anthos_admin' in group_names"

# git pull user data from a git repo. Existing GCP service account keys, ssh keys, ssl certs
# Depends on having an ssh config file present in user's .ssh directory configured for git access
# This only executes on the ansible controller (i.e. localhost).
- name: Pull userdata repo
  become: no
  git:
    repo: "{{ anthos_userdata_git.repo_url }}"
    dest: "/home/{{ ansible_user }}/{{ secrets_directory }}"
  when: 
    - anthos_userdata_git.pull_enable
    - "'local' in group_names"
  register: userdata_gitpulled

- name: Check if secrets were pulled from git
  stat:
    path: "{{ secrets_path }}/.git"
  when:
    - "'local' in group_names"
  register: git_secrets

- name: Fix permissions on ssh private key if pulled from git repo
  file:
    path: "{{ secrets_path }}/{{ gke_admin_workstation.ssh_private_key }}"
    mode: 0600
  when: 
    - "'local' in group_names"
    - git_secrets.stat.isdir
