---

- name: Read gkeadm file from disk
  become: false
  vars:
    contents: "{{ lookup('file', '{{ output_directory }}/{{ adminWorkstation.name }}') }}"
    regexp: 'ubuntu@\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\b'
  set_fact:
    gke_adm_wrkst_ip_ff: "{{ contents | regex_search(regexp, '\\1') }}"

- name: Add host to running inventory
  become: false
  add_host:
    hostname: "{{ inventory_hostname }}"
    groups:
      - anthos_admin
    ansible_host: "{{ gke_adm_wrkst_ip_ff | join('.') }}"