###                                                                             
# Copyright (2020) Hewlett Packard Enterprise Development LP                    
#                                                                               
# Licensed under the Apache License, Version 2.0 (the "License");               
# You may not use this file except in compliance with the License.              
# You may obtain a copy of the License at                                       
#                                                                               
# http://www.apache.org/licenses/LICENSE-2.0                                    
#                                                                               
# Unless required by applicable law or agreed to in writing, software           
# distributed under the License is distributed on an "AS IS" BASIS,             
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.      
# See the License for the specific language governing permissions and           
# limitations under the License.                                                
###                                                                             
---
# Currently gkeadm cannot download the GKE admin workstation OVA properly if the /tmp and working directory are in different
# filesystems.  This task will check for that condition and set the download_ova var appropriately

- name: Check filesystems for gke admin ova download
  command: |
    df .
  register: cwd_df

- name: set tmp fact
  set_fact:
    cwd_mount: "{{ cwd_df.stdout | regex_search('(\/dev\/[^\\s]+)', '\\1', multiline=true) | checksum }}"

- name: cwd mount out
  debug:
    msg: "{{ cwd_mount }}"
    verbosity: 3

- name: Check filesystems for gke admin ova download
  command: |
    df /tmp
  register: tmp_df

- name: set tmp fact
  set_fact:
    tmp_mount: "{{ tmp_df.stdout | regex_search('(\/dev\/[^\\s]+)', '\\1', multiline=true) | checksum }}"

- name: tmp output
  debug:
    msg: "{{ tmp_mount }}"
    verbosity: 3

- name: Force OVA download flag to false
  set_fact:
    gkeadm_download_ova: true

- name: Set OVA download flag
  set_fact:
    gkeadm_download_ova: false
  when: cwd_mount != tmp_mount

- name: OVA flag state
  debug:
    msg: "{{ gkeadm_download_ova }}"