# Base Anthos Version
anthos_version: '1.3.0-gke.16'

# Base Path for files that are sensitive e.g ssl certificates, files with passwords, Anthos service-account
# key files
# Path used when accessing files on GKE Admin workstation
remote_secrets_path: '/home/{{ ansible_user }}/gke_admin_wrkst_private'

# Path used when accessing files on Ansible control host
local_secrets_path: "/home/{{ lookup ('env', 'USER') }}/gke_admin_wrkst_private"

# Virtual Center Configuration
vcenter:
  address: '10.1.223.196'
  username: "{{ vault_vcenter_username }}"
  password: "{{ vault_vcenter_password }}"
  datacenter: 'Datacenter'
  datastore: 'ds1'
  cluster: 'New Cluster'
  network: 'VM Network 2'
  resourcepool: 'New Cluster/Resources/'
  cacertpath_gkeadm: "{{ local_secrets_path }}/vmware/vcenter.pem"
  cacertpath_gkectl: "{{ remote_secrets_path }}/vmware/vcenter.pem"

# GKE Admin Workstation Configuration
gke_admin_workstation:
  secrets_path: '/home/ubuntu/gke_admin_wrkst_private'
  proxyUrl: 'http://16.100.208.216:8888'
  name: 'gke-adm-test'
  cpus: '4'
  memoryMB: '8192'
  diskGB: '50'
  ntpServer: 'hou-ntp1.hcilabs.hpecorp.net'
  ipAllocationMode: 'dhcp'
  # For Static IP assignment uncomment and enter info below. Remove ipAllocationMode: 'dhcp' above.
  #ipAllocationMode: 'static'
  #ip: '192.168.1.10'
  #gateway: '192.168.1.1'
  #netmask: '255.255.255.0'
  #dns:
  #  - nameserver_ip
  #  - nameserver_ip

# Path to gke admin workstation ova file to install. If defined and valid gkeadm will use this file.
# If empty '' or invalid gkeadm will download the file.
# gkeadm_ova_path: '/home/sgifford/Downloads/1.3.0-gke.16/gke-on-prem-admin-appliance-vsphere-1.3.0-gke.16.ova'
gkeadm_ova_path: ''

# Path the yaml file created by running 'gkeadm create config'
gkeadm_config: '{{ local_secrets_path }}/admin-ws-configtest.yaml'

# Path to ssh private key to install on admin workstation
# This key will also be used by ansible to connect to admin workstation
ansible_ssh_private_key_file: '{{ local_secrets_path }}/dot-cfg-files/.ssh/vsphere_workstation'

# Docker bip (base IP) can be changed if the default conflict with your environment
docker_bip: '192.68.0.1/16'

# A private Docker registry is commonly used in Air-Gapped installations
private_docker_registry: true
private_reg_ip: '16.100.209.193'
private_reg_port: '5005'
private_reg_cert_path_gkeadm: '{{ local_secrets_path }}/private_docker_reg/registry.crt'
private_reg_cert_path_gkectl: '{{ remote_secrets_path }}/private_docker_reg/registry.crt'
private_reg_username: 'me'
private_reg_password: 'you'

# Proxy definitions -- gkeadm will have it's own. For now these are needed for post deploy configuration
proxy_address: '16.100.208.216'
proxy_port: '8888'
proxy_type: 'http'
no_proxy: '.hcilabs.hpecorp.net,.simplivt.local'

# Path to directory containing desired .ssh directory contents. Used for git repo cloning.
ssh_config_path: '{{ local_secrets_path }}/dot-cfg-files/.ssh'

# Path to repos to pull after deployment. Do not change anthos_deploy_git, but update the anthos_userdata_git entry.
anthos_deploy_git:
  repo_name: anthos_wrkstation_files
  repo_url: 'ssh://git@stash.simplivt.local:7999/soleng/anthos_wrkstation_files.git'
anthos_userdata_git:
  repo_name: gke_admin_wrkst_private
# Change this url to match your private user data repo path
  repo_url: 'ssh://git@stash.simplivt.local:7999/~sgifford/gke_admin_wrkst_private.git'

# Location of files generated by gkeadm during deployment of GKE Admin Workstation
output_directory: '/home/{{ ansible_user }}/output'

# Location of files generated on GKE Admin Workstation by gkectl during GKE on-prem cluster creation
log_directory: '/home/{{ ansible_user }}/logs'

# GKE Admin Workstation destination of admin and user cluster configuration yaml files. 
cluster_configurations_path: '/home/ubuntu/cluster-configurations'

# GKE Admin Workstation destination of admin and user cluster kubeconfig files generated when gkectl deploys clusters
cluster_kubeconfig_path: '/home/ubuntu/kubeconfigs'

# Setting name of admin kubeconfig here to be able to use it programatically later
admin_cluster_kubeconfig: 'kubeconfig'

# Enable/Disable/Flags for the gkectl check-config execution. Recommend to run at least the first time.
# Flags to be added to gkectl command. See docs for explanation.
enable_config_check: true
gkectl_check_flags: '--skip-validation-vips --fast'

# Enable/Disable/Flags for the gkectl prepare execution. Required to run at least one time.
# Flags to be added to gkectl command. See docs for explanation.
gkectl_run_prepare: true
gkectl_prepare_flags: '--skip-validation-all'

# Enable/Disable/Flags for the gkectl create cluster execution. Required to enable admin at least on first run.
# Flags to be added to gkectl command. See docs for explanation.
create_admin_cluster: true
create_user_cluster: true
gkectl_create_flags: '--skip-validation-all'

# GCP project to set.  gkeadm does not currently set this.
gcloud_project: 'deep-thought-259715'

# Common variables to all clusters
gke_bundle_path: '/var/lib/gke/bundles/gke-onprem-vsphere-{{ anthos_version }}-full.tgz'
gke_network_internal: 'gke-internal'
gke_cluster_resource_pool: 'Anthos_1.3'
gke_data_disk_name: 'test-deploy'
gke_cluster_vcenter_ssl_pub_key: '{{ gke_admin_workstation.secrets_path }}/vmware/vcenter.pem'
gke_register_sa_keypath: '{{ gke_admin_workstation.secrets_path }}/gkeonprem-keys/register-key.json'
gke_agent_sa_keypath: '{{ gke_admin_workstation.secrets_path }}/gkeonprem-keys/connect-key.json'
gke_auditlogging_sa_keypath: '{{ gke_admin_workstation.secrets_path }}/gkeonprem-keys/whitelisted-key.json'
gke_stackdriver_sa_keypath: '{{ gke_admin_workstation.secrets_path }}/gkeonprem-keys/stackdriver-key.json'
gke_whitelisted_keypath: '/home/{{ ansible_user }}/gke_admin_wrkst_private/gkeonprem-keys/whitelisted-key.json'
# Admin Cluster variables
gke_admin_cluster_network: ''

# User Cluster variables ## FUTURE: move to gke_cluster_config for PER User cluster templating.
gke_user_cluster_network: ''
gke_user_cluster_masternode_cpu: '4'
gke_user_cluster_masternode_memory: '8192'
gke_user_cluster_masternode_replicas: '1'
gke_user_cluster_workernode_cpu: '4'
gke_user_cluster_workernode_memory: '8192'
gke_user_cluster_workernode_replicas: '3'
gke_cluster_location: 'us-east1'
enable_vpc: 'false'
enable_cloudrun: 'false'
gcp_region: 'us-east1'

# GKE on-prem cluster configuration information. Ensure 'admin' and 'user' strings exist in admin and user
# cluster filenames respectively.  The name: parameter should be the exact filename as exists in the local_path:
# Only 1 admin cluster should be defined.  Multiple user clusters can be defined.
gke_cluster_config:
    - name: 'admin'
      type: 'admin'
      f5_partition: 'Spanned_VIP'
      state: present
      cluster_ctrl_vip: '172.17.0.21'
      cluster_ingress_vip: '172.17.0.22'
    - name: 'sg-test4-13'
      type: 'user'
      f5_partition: 'Spanned_VIP_user'
      cluster_ctrl_vip: '172.17.0.69'
      cluster_ingress_vip: '172.17.0.72'
      state: present
    - name: 'sg-test5-13'
      type: 'user'
      f5_partition: 'user2_VIP'
      cluster_ctrl_vip: '172.17.0.32'
      cluster_ingress_vip: '172.17.0.33'
      state: present

#
# F5 Configuration Information
#
f5:
  provider:
    user: admin
    password: "{{ vault_f5_admin_password }}"
    server: 10.1.222.170
    validate_certs: no
    server_port: 443
  
  hostname: Morbo-F5-SG1.thehead.local
  admin_username: admin
  admin_password: "{{ vault_f5_admin_password }}"
  
  # Set to true to ensure config is saved to f5
  save: true
  
  internal_vlan_name: internal
  internal_vlan_tag: 1700
  internal_vlan_selfip: 172.17.0.16
  internal_vlan_selfip_netmask: 255.255.224.0
  internal_vlan_selfip_name: gke-internal
  
  external_vlan_name: external
  external_vlan_tag: 1732
  external_vlan_selfip: 172.17.32.16
  external_vlan_selfip_netmask: 255.255.224.0
  external_vlan_selfip_name: gke-external
  
  license: 
    - { key: "{{ vault_f5_license_key }}", state: present }
  