# Base Anthos Version
anthos_version: '1.3.0-gke.16'

# Path to gke admin workstation ova file to install
gkeadm_ova_path: '/home/sgifford/Downloads/1.3.0-gke.16/gke-on-prem-admin-appliance-vsphere-1.3.0-gke.16.ova'

# Docker bip (base IP) can be changed if the default conflict with your environment
docker_bip: '192.68.0.1/16'

# A private Docker registry is commonly used in Air-Gapped installations
# FIXME: Note ssl cert for this registry is currently held in ansible role directory
private_docker_registry: true
private_reg_ip: '16.100.209.193'
private_reg_port: '5005'
private_reg_cert_path: '{{ secrets_files_path }}/private_docker_reg/registry.crt'

# Proxy definitions -- gkeadm will have it's own. For now these are needed for post deploy configuration
proxy_address: '16.100.208.216'
proxy_port: '8888'
proxy_type: 'http'
no_proxy: '.hcilabs.hpecorp.net,.simplivt.local'

# GCP project to set.  gkeadm does not currently set this.
gcloud_project: 'deep-thought-259715'

# Path the yaml file created by running 'gkeadm create config'
gkeadm_config: '/home/sgifford/gke_admin_wrkst_private/admin-ws-config.yaml'

# Path to directory containing desired .ssh directory contents. Used for git repo cloning.
ssh_config_path: '/home/sgifford/gke_admin_wrkst_private/dot-cfg-files/.ssh'

# Path to ssh private key to install on admin workstation
# This key will also be used by ansible to connect to admin workstation
ansible_ssh_private_key_file: '/home/sgifford/gke_admin_wrkst_private/dot-cfg-files/.ssh/vsphere_workstation'

# Path to repos to pull after deployment. Do not change anthos_deploy_git, but update the anthos_userdata_git entry.
anthos_deploy_git:
  repo_name: anthos_workstation_files
  repo_url: 'ssh://git@stash.simplivt.local:7999/soleng/anthos_wrkstation_files.git'
anthos_userdata_git:
  repo_name: gke_admin_wrkst_private
# Change this url to match your private user data repo path
  repo_url: 'ssh://git@stash.simplivt.local:7999/~sgifford/gke_admin_wrkst_private.git'

# Location of files generated by gkeadm during deployment of GKE Admin Workstation
output_directory: '/home/{{ ansible_user }}/output'

# Location of files generated on GKE Admin Workstation by gkectl during GKE on-prem cluster creation
log_directory: '/home/{{ ansible_user }}/logs'

# Base Path for files that are sensitive e.g ssl certificates, files with passwords, Anthos service-account
# key files
secrets_files_path: '/home/sgifford/gke_admin_wrkst_private'

# GKE Admin Workstation destination of admin and user cluster configuration yaml files. 
cluster_configurations_path: '/home/ubuntu/cluster-configurations'

# GKE Admin Workstation destination of admin and user cluster kubeconfig files generated when gkectl deploys clusters
cluster_kubeconfig_path: '/home/ubuntu/kubeconfigs'

# Setting name of admin kubeconfig here to be able to use it programatically later
admin_cluster_kubeconfig: 'kubeconfig'

# Enable/Disable/Flags for the gkectl check-config execution. Recommend to run at least the first time.
# Flags to be added to gkectl command. See docs for explanation.
enable_config_check: false
gkectl_check_flags: '--skip-validation-vips --fast'

# Enable/Disable/Flags for the gkectl prepare execution. Required to run at least one time.
# Flags to be added to gkectl command. See docs for explanation.
gkectl_run_prepare: false
gkectl_prepare_flags: '--skip-validation-all'

# Enable/Disable/Flags for the gkectl create cluster execution. Required to enable admin at least on first run.
# Flags to be added to gkectl command. See docs for explanation.
create_admin_cluster: false
create_user_cluster: true
gkectl_create_flags: '--skip-validation-all'

# GKE on-prem cluster configuration information. Ensure 'admin' and 'user' strings exist in admin and user
# cluster filenames respectively.  The name: parameter should be the exact filename as exists in the local_path:
# Only 1 admin cluster should be defined.  Multiple user clusters can be defined.
gke_cluster_config:
    - name: 'admin-config.yaml'
      local_path: '/home/sgifford/gke_admin_wrkst_private/gkeonprem-config/admin-config.yaml'
    - name: 'user1-config.yaml'
      local_path: '/home/sgifford/gke_admin_wrkst_private/gkeonprem-config/user1-config.yaml'
    - name: 'user2-config.yaml'
      local_path: '/home/sgifford/gke_admin_wrkst_private/gkeonprem-config/user2-config.yaml'

