###                                                                             
# Copyright (2020) Hewlett Packard Enterprise Development LP                    
#                                                                               
# Licensed under the Apache License, Version 2.0 (the "License");               
# You may not use this file except in compliance with the License.              
# You may obtain a copy of the License at                                       
#                                                                               
# http://www.apache.org/licenses/LICENSE-2.0                                    
#                                                                               
# Unless required by applicable law or agreed to in writing, software           
# distributed under the License is distributed on an "AS IS" BASIS,             
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.      
# See the License for the specific language governing permissions and           
# limitations under the License.                                                
###                                                                             
---
# tasks file for anthos_f5_config
- name: Get BIG-IP information
  bigip_device_info:
    gather_subset:
      - devices
    provider: "{{ f5.provider }}"
  register: bigip_facts
  delegate_to: localhost

- name: Get BIG-IP software version
  set_fact:
    bigip_version: "{{ bigip_facts.devices | json_query(versquery) }}"
  vars:
    versquery: '[*].software_version'

- name: Debug print bigip_version
  debug:
    msg: "{{ bigip_version }}"
    verbosity: 2

- name: Provision LTM at nominal level
  bigip_provision:
    module: ltm
    level: nominal
    provider: "{{ f5.provider }}"
  delegate_to: localhost

- name: Provision MGMT memory to large
  bigip_provision:
    module: mgmt
    memory: large
    provider: "{{ f5.provider }}"
  delegate_to: localhost

- name: Adjust restjavad memory setting
  bigip_command:
    commands:
      - modify sys db restjavad.useextramb value true
      - bigstart restart restjavad
    provider: "{{ f5.provider }}"
  when: 
      - bigip_version is match("12")
  delegate_to: localhost

- name: Retrive restjavad memory setting
  bigip_command:
    commands:
      - list /sys db provision.tomcat.extramb
    provider: "{{ f5.provider }}"
  when: 
      - bigip_version is search("13.1")
  register: f5_tomcat_ram
  delegate_to: localhost

- name: Debug print f5_tomcat_ram
  debug:
    msg: "{{ f5_tomcat_ram.stdout | string | regex_search(regexp) }}"
    verbosity: 2
  vars:
    regexp: '(\d+)'
  when: f5_tomcat_ram.stdout is defined

- name: Debug print f5_tomcat_ram_value
  debug:
    msg: "{{ f5_tomcat_ram.stdout | string }}"
    verbosity: 2
  when: 
    - f5_tomcat_ram.stdout is defined
    - f5_tomcat_ram.stdout is search('value "20"')

- name: Set f5_tomcat_ram fact
  set_fact:
    f5_tomcat_ram_value: "{{ f5_tomcat_ram.stdout | string | regex_search(regexp) }}"
  vars:
    regexp: '(\d+)'
  when: 
    - f5_tomcat_ram.stdout is defined

- name: Adjust restjavad memory setting
  bigip_command:
    commands:
      - modify /sys db provision.tomcat.extramb value 20
      - restart /sys service tomcat
    provider: "{{ f5.provider }}"
  when: 
      - bigip_version is search("13.1")
      - f5_tomcat_ram_value != "20"
      - f5_tomcat_ram.stdout is defined
  delegate_to: localhost