---
# tasks file for F5_license_config
- name: License BIG-IP using a key
  bigip_device_license:
      provider: "{{ f5.provider }}"
      license_key: "{{ item.key }}"
      state: "{{ item.state }}"
      accept_eula: yes
  delegate_to: localhost
  with_items:
    - "{{ f5.license }}"