# Absolute path to a GKE bundle on disk
bundlepath: "/var/lib/gke/bundles/gke-onprem-vsphere-1.3.0-gke.16-full.tgz"
# Specify which vCenter resources to use for deployment
vcenter:
  # The credentials and address GKE should use to connect to vCenter
  credentials:
    address: "10.1.223.196"
    username: "USERNAME@vsphere.local"
    password: "PASSWORD"
  datacenter: "Datacenter"
  datastore: "ds1"
  cluster: "New Cluster"
  network: "gke-internal"
  resourcepool: "Anthos_1.3"
  # Provide the name for the persistent disk to be used by the deployment (ending
  # in .vmdk). Any directory in the supplied path must be created before deployment.
  # Not required when adding additional user clusters
  datadisk: "test-deploy"
  # Provide the path to vCenter CA certificate pub key for SSL verification
  cacertpath: "/home/ubuntu/gke_admin_wrkst_private/vmware/vcenter.pem"
# Specify the proxy configuration.
proxy:
  # The URL of the proxy
  url: "http://16.100.208.216:8888"
  # The domains and IP addresses excluded from proxying
  noproxy: "16.100.209.193"
# Specify admin cluster settings for a fresh GKE On-Prem deployment. Omit this section
# and use the --kubeconfig flag when adding a new user cluster to an existing deployment
admincluster:
  # In-Cluster vCenter configuration
  vcenter:
    # If specified it overwrites the network field in global vcenter configuration
    network: ""
  # # The absolute or relative path to the yaml file to use for static IP allocation.
  # # Do not include if using DHCP
  # ipblockfilepath: ""
  # # Specify pre-defined nodeports if using "manual" load balancer mode
  # manuallbspec:
  #   ingresshttpnodeport: 32527
  #   ingresshttpsnodeport: 30139
  #   controlplanenodeport: 30968
  #   addonsnodeport: 31405
  # Specify the already-existing partition and credentials to use with F5
  bigip:
    # To re-use credentials across clusters we recommend using YAML node anchors.
    # See https://yaml.org/spec/1.2/spec.html#id2785586
    credentials:
      address: "10.1.222.170"
      username: "admin"
      password: "PASSWORD"
    partition: "Spanned_VIP"
    # # Optionally specify a pool name if using SNAT
    # snatpoolname: ""
  # The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlplanevip: "172.17.0.21"
    # Shared by all services for ingress traffic
    ingressvip: "172.17.0.22"
    # # Used for admin cluster addons (needed for multi cluster features). Must be the same
    # # across clusters
    # addonsvip: ""
  # The Kubernetes service CIDR range for the cluster. Must not overlap with the pod
  # CIDR range
  serviceiprange: 10.96.232.0/24
  # The Kubernetes pod CIDR range for the cluster. Must not overlap with the service
  # CIDR range
  podiprange: 192.168.0.0/16
# Specify settings when deploying a new user cluster. Used both with a fresh deployment
# or when adding a new cluster to an existing deployment.
# Which load balancer mode to use "Manual" or "Integrated"
lbmode: Integrated
# Specify which GCP project to connect your GKE clusters to
gkeconnect:
  projectid: "deep-thought-259715"
  # The absolute or relative path to the key file for a GCP service account used to
  # register the cluster
  registerserviceaccountkeypath: "/home/ubuntu/gke_admin_wrkst_private/gkeonprem-keys/register-key.json"
  # The absolute or relative path to the key file for a GCP service account used by
  # the GKE connect agent
  agentserviceaccountkeypath: "/home/ubuntu/gke_admin_wrkst_private/gkeonprem-keys/connect-key.json"
  #proxy: "http://u:p@16.100.208.216:8888"
# Specify which GCP project to connect your logs and metrics to
stackdriver:
  projectid: "deep-thought-259715"
  # A GCP region where you would like to store logs and metrics for this cluster.
  clusterlocation: "us-east1"
  enablevpc: false
  # The absolute or relative path to the key file for a GCP service account used to
  # send logs and metrics from the cluster
  serviceaccountkeypath: "/home/ubuntu/gke_admin_wrkst_private/gkeonprem-keys/stackdriver-key.json"
# Specify Cloud Run configuration
cloudrun:
  enabled: false
# # Optionally use a private Docker registry to host GKE images
privateregistryconfig:
  # Do not include the scheme with your registry address
  credentials:
    address: "16.100.209.193:5005"
    username: "USERNAME"
    password: "PASSWORD"
#   # The absolute or relative path to the CA certificate for this registry
  cacertpath: "/home/ubuntu/gke_admin_wrkst_private/private_docker_reg/registry.pem"
# The absolute or relative path to the GCP service account key that will be used to
# pull GKE images
gcrkeypath: "/home/ubuntu/gke_admin_wrkst_private/gkeonprem-keys/whitelisted-key.json"
# Configure kubernetes apiserver audit logging
cloudauditlogging:
  projectid: "deep-thought-259715"
  # A GCP region where you would like to store audit logs for this cluster.
  clusterlocation: "us-east1"
  # The absolute or relative path to the key file for a GCP service account used to
  # send audit logs from the cluster
  serviceaccountkeypath: "/home/ubuntu/gke_admin_wrkst_private/gkeonprem-keys/whitelisted-key.json"
