gcp:
  # Path of the whitelisted service account's JSON key file
  whitelistedServiceAccountKeyPath: ""
# Specify which vCenter resources to use
vCenter:
  # The credentials and address GKE On-Prem should use to connect to vCenter
  credentials:
    address: ""
    username: ""
    password: ""
  datacenter: ""
  datastore: ""
  cluster: ""
  network: ""
  resourcePool: ""
  # Provide the path to vCenter CA certificate pub key for SSL verification
  caCertPath: ""
# The URL of the proxy for the jump host
proxyUrl: ""
adminWorkstation:
  name: gke-admin-ws-1.3.0-200415-150312
  cpus: 4
  memoryMB: 8192
  # The disk size of the admin workstation in GB. It is recommended to use a disk
  # with at least 50 GB to host images decompressed from the bundle.
  diskGB: 50
  network:
    # The IP allocation mode: 'dhcp' or 'static'
    ipAllocationMode: ""
    # # The host config in static IP mode. Do not include if using DHCP
    # hostConfig:
    #   # The IPv4 static IP address for the admin workstation
    #   ip: ""
    #   # The IP address of the default gateway of the subnet in which the admin workstation
    #   # is to be created
    #   gateway: ""
    #   # The subnet mask of the network where you want to create your admin workstation
    #   netmask: ""
    #   # The list of DNS nameservers to be used by the admin workstation
    #   dns:
    #   - ""
  # The URL of the proxy for the admin workstation
  proxyUrl: ""
  ntpServer: ntp.ubuntu.com
