---
- hosts: anthos_admin
  become: yes
  gather_facts: false

  roles:
    - role: admin_workstation/deploy_admin_wrkst
      delegate_to: localhost
    - role: common/docker_config
    - role: common/apt_proxy
    - role: admin_workstation/admin_host_config
    - role: common/userdata
    - role: common/splash_summary