---
- hosts: anthos_admin
  become: yes
  gather_facts: false

  vars_files:
    - "{{ gkeadm_config }}"

  roles:
    - role: admin_workstation/deploy_admin_wrkst
    - role: common/docker_config
    - role: common/apt_proxy
    - role: admin_workstation/admin_host_config
    - role: common/userdata
    - role: common/splash_summary