---
# tasks file for anthos_deploy_admin_wrkst
- name: Include the filesytem check for gkeadm requirements
  import_tasks: tasks/prereq_for_download.yml

- name: Check if gke admin workstation exists using global vcenter config
  become: false
  vmware_guest_info:
    hostname: "{{ vcenter.address }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter }}"
    name: "{{ gke_admin_workstation.name }}"
    validate_certs: no
  register: admin_wrkst_info
  failed_when: false
  when: not gke_admin_workstation.alt_vcenter.enable

- name: Check if gke admin workstation exists using gkeadm alt_vcenter
  become: false
  vmware_guest_info:
    hostname: "{{ gke_admin_workstation.alt_vcenter.address }}"
    username: "{{ gke_admin_workstation.alt_vcenter.username }}"
    password: "{{ gke_admin_workstation.alt_vcenter.password }}"
    datacenter: "{{ gke_admin_workstation.alt_vcenter.datacenter }}"
    name: "{{ gke_admin_workstation.name }}"
    validate_certs: no
  register: admin_wrkst_info
  failed_when: false
  when: gke_admin_workstation.alt_vcenter.enable

- debug:
    msg: "{{ admin_wrkst_info }}"
    verbosity: 2

- name: Set flag for running gkeadm based on existance (or not) of VM
  set_fact:
    run_gkeadm: true
  when: >
    admin_wrkst_info.msg is defined and 'non-existing VM' in admin_wrkst_info.msg
    or 'non-existing VM' in admin_wrkst_info
    or admin_wrkst_info.failed
  failed_when: false

- name: Create input file for gkeadm for creating GKE Admin workstation
  template:
    src: admin-ws-config.yaml.j2
    dest: "{{ gkeadm_config }}"

- debug:
    msg: "Flag for gkeadm to download OVA is {{ gkeadm_download_ova }}"
    verbosity: 2

- name: Use Google gkeadm to deploy gke admin workstation using pre-downloaded OVA
  become: false
  command: "{{ gkeadm_osimage_path_command }}"
  register: gkeadm_output
  args:
    chdir: "{{ output_directory }}"
  when: >
    run_gkeadm is defined
    and gkeadm_ova_path is exists

- name: Use Google gkeadm to deploy gke admin workstation and download the OVA
  become: false
  command: "{{ gkeadm_download_ova_command }}"
  register: gkeadm_output
  args:
    chdir: "{{ output_directory }}"
  environment:
    TMPDIR: "{{ output_directory }}"
  when: >
    run_gkeadm is defined
    and not gkeadm_ova_path is exists

- debug: 
    msg: "{{ gkeadm_output }}"
    verbosity: 3

- name: Output name of admin workstation
  debug:
    msg: "{{ gke_admin_workstation.name }}"
    verbosity: 2 

- name: Get the IP for the current admin WS
  import_tasks: tasks/admin_ws_ip.yml
